
version: '3.8'

services:
  datascience:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8895:8888"  # For Jupyter Notebook
      - "6010:6006"  # For TensorBoard
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - ENV_NAME=data_science_nfl_quant
      - PYTHON_VER=3.10
    command: ["conda", "run", "-n", "data_science_nfl_quant", "jupyter", "lab", "--ip", "0.0.0.0", "--port", "8888", "--no-browser", "--allow-root"]

    